### ISSUE TITLE
Setup script missing plv8 extension

### ISSUE THREAD

**Issue by connorholyday** [graphile/examples#1]
Running the `./setup.sh` script results in this:
```
ERROR:  could not open extension control file "/usr/local/share/postgresql/extension/plv8.control": No such file or directory
```

Is [this](https://plv8.github.io/) what I need to setup?

**Comment by benjie** [comment]
Actually we don’t need plv8 or a bunch of those other extensions; that’s just my standard setup script 😳. Drop the lines that contain plv8 from https://github.com/graphile/examples/blob/master/setup.sh

**Comment by connorholyday** [comment]
Ah I see! After removing those lines and re-running the script it's giving me:
```
ERROR:  role "graphiledemo" already exists
```

Any suggestions?

**Comment by benjie** [comment]
Run:
```
psql -X1 -v ON_ERROR_STOP=1 graphiledemo -f db/schema.sql
```

And open .env and delete the bottom half (the copy of the top half).

Then you’re good to go

**Comment by benjie** [comment]
Fixed in https://github.com/graphile/examples/commit/61215a3863c253e51e49eb8182ff1bd242aaa1e6
