### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by tyvdh** [graphile/examples#15]
http://localhost:8349/forums/testimonials/1

```
Error GraphQL error: Variable "$topic" got invalid value "1"; Expected type Int; Int cannot represent non-integer value: "1"
```

Looks like topic is a string when it needs to be cast to an integer.

**Comment by benjie** [comment]
That's exactly correct - that's an issue from upgrading from GraphQL 0.13 to 14.x - variables are more strictly validated now (they used to be co-erced).

If you're able, could you file a PR changing this line:

https://github.com/graphile/examples/blob/8d23c96f8c646d4291eee1b6e894a6cd3a2309d1/client-react/src/routes/TopicRoute.js#L23

to something like

```js
      <Query query={TopicQuery} variables={{ topic: parseInt(topic, 10) }}>
```

?

**Comment by tyvdh** [comment]
https://github.com/graphile/examples/pull/16

**Comment by benjie** [comment]
Merged
