### ISSUE TITLE
Use 127.0.0.1 for brew

### ISSUE THREAD

**Issue by brandonkal** [graphile/examples#18]
This took some time to debug, so hopefully it will help those who prefer to manage postresql with homebrew for a fast installation.

Installing postgresql:
```
brew install postgresql
brew services start postgresql
```

```
git clone https://github.com/graphile/examples.git
cd examples
yarn
./setup.sh
```

The setup.sh will fail to connect to the database to initialize the database schema unless "localhost" is replaced with the IP "127.0.0.1"

There appears to be some issue with mapping localhost which may be related to the homebrew postgres install.

**Comment by benjie** [comment]
When using localhost it uses a unix socket rather than network connection. I use postgres from Homebrew and have done so on a few different machines with no issues; I wonder if something isn’t quite right with your install? Have you tried rebooting?

**Comment by benjie** [comment]
There’s a few suggestions here: https://stackoverflow.com/questions/13410686/postgres-could-not-connect-to-server

**Comment by brandonkal** [comment]
I will have to double check everything and report back. What is odd is that a plain `psql` command works from the terminal, suggesting that the unix socket is up.

I also noticed that the GitHub auth on localhost, but the IP worked fine.

**Comment by benjie** [comment]
Could just be a missing environmental variable or similar - have you tried rebooting?

**Comment by brandonkal** [comment]
Thanks @benjie it is working now so it must have been a fluke. I have had postgres installed with homebrew for some time but only just discovered `brew services` so it may have been the couple of restarts since running `brew services start postgresql`

**Comment by benjie** [comment]
Thanks for letting me know 👍
