### ISSUE TITLE
PostgreSQL registration/login fails

### ISSUE THREAD

**Issue by LeoVS09** [graphile/examples#22]
When I use this repo, all registrations and some logins fails, without any postgres errors. In `/shared/plugins/PassportLoginPlugin.js` all sql query of 
```
          const {
            rows: [user],
          } = await rootPgPool.query(
            `select users.* from app_private.really_create_user(
              username => $1,
              email => $2,
              email_is_verified => false,
              name => $3,
              avatar_url => $4,
              password => $5
            ) users where users is not null`,
            [username, email, name, avatarUrl, password]
          );
```
and
```
          const {
            rows: [user],
          } = await rootPgPool.query(
            `select users.* from app_private.login($1, $2) users where users is not null`,
            [username, password]
          );
```
Always return user as undefined. 
Problem in this row `users where users is not null`,  in PostgreSQL expression ` users is not null` and `not (users is null)` not equal. When some field in users is null expression  ` users is not null` return false, so this query will not return user even when query successful.

---

[PostgreSQL documentation](https://www.postgresql.org/docs/9.6/functions-comparison.html) quote:
> If the expression is row-valued, then IS NULL is true when the row expression itself is null or when all the row's fields are null, while IS NOT NULL is true when the row expression itself is non-null and all the row's fields are non-null.

Addition information you can find in this [question](https://dba.stackexchange.com/questions/157691/x-is-not-null-vs-not-x-is-null-in-postgresql)

**Comment by benjie** [comment]
Ugh; thanks for pointing this out — I seem to get bitten by it about once every 6 months!

https://twitter.com/Benjie/status/1111305470512377856
